FROM node:20-alpine AS builder 
WORKDIR /app 
ARG DATABASE_URL="postgresql:palceholder:5432/db"
COPY package*.json ./ 

RUN npm install 

COPY  prisma ./prisma 
COPY get.js ./
COPY client.js ./ 
COPY prisma.config.ts ./ 


#RUN npm install dotenv
RUN npx prisma generate  

FROM node:20-alpine 
WORKDIR /app 
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/prisma ./prisma 
COPY --from=builder /app/client.js ./
COPY --from=builder /app/get.js ./
COPY --from=builder /app/prisma.config.ts ./

EXPOSE 4047
CMD ["node","get.js"]