apiVersion: apps/v1
kind: Deployment
metadata:
  name: adduser
  namespace: suborna
spec:
  replicas: 2
  selector:
    matchLabels:
      app: adduser-express
  template:
    metadata:
      labels:
        app: adduser-express
    spec:
      initContainers:
        - name: db-sync-aduser
          image: getservice
          imagePullPolicy: Never
          resources:
            limits:
              cpu: "100m"
              memory: "128Mi"
            requests:
              cpu: "50m"
              memory: "64Mi"
          command: ["/bin/sh","-c"]
          args: ["npx prisma db push"]
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: sbrn-sec
                  key: DATABASE_URL
      containers:
        - name: adduser-container
          image: adduser
          imagePullPolicy: Never
          resources:
            requests:
              memory: "100Mi"
              cpu: "1"
            limits:
              memory: "200Mi"
              cpu: "2"
          env:
            - name: DATABASE_URL
              value: "postgresql://postgres:suborna@postgrescn-rw:5432/appdb?schema=public"
          ports:
            - containerPort: 4045