apiVersion: postgresql.cnpg.io/v1 
kind: Cluster 
metadata: 
 name: postgrescn 
spec: 
  instances: 3 
  imageName: ghcr.io/cloudnative-pg/postgresql:13.6
  storage: 
    size: 1Gi 
    storageClass: standard 
  
  superuserSecret: 
    name: superuser-sec 

  bootstrap: 
    initdb: 
      database: appdb 
      owner: postgres 
      secret: 
       name: norm-user
  primaryUpdateStrategy: unsupervised

