apiVersion: v1 
kind: PersistentVolumeClaim 
metadata:
 name: suborna-pvc 
spec: 
  storageClassName: ""
  volumeName: suborna-volume
  accessModes: 
  - ReadWriteOnce
  resources:
   requests:
     storage: 1Gi 
