apiVersion: v1
kind: Secret
metadata:
  name: sbrn-sec
  namespace: suborna
type: Opaque
stringData:
  # Updated with your Neon DB connection string
  DATABASE_URL: "postgresql://neondb_owner:npg_ckr6bCFB7Vgz@ep-small-darkness-ahriz0ey.c-3.us-east-1.aws.neon.tech/neondb?sslmode=require"