apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler 
metadata: 
  name: gt-vpa
  namespace: suborna
spec:
  targetRef: 
    apiVersion: apps/v1
    kind: Deployment
    name: vish-stress
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
    - containerName: vish-container
      controlledResources: ["memory"] 